### ISSUE TITLE
Invalid Spawn Locations

### ISSUE THREAD

**Issue by asinck** [allejo/matchTrainerAssistant#1]
Spawning using the command allows the user to specify an invalid spawn location (ie, outside the play area), and such a spawn results in an auto-kick.

**Comment by allejo** [comment]
I'll label this as an enhancement since the command is working as intended but players are silly enough to input invalid values.

Suggested fixes:
- [x] Find the max height BZFS supports for a Z value and assert against that
- [x] Get the `_worldSize` and ensure the values are not larger than that

If you're interested in taking a stab at patching this, feel free to do so!

**Comment by asinck** [comment]
Also: the maximum values that the player should use with this command are told to the player.

**Comment by allejo** [comment]
Note to self: just need to test and then it's good to merge
